FROM maven:3.8.3-openjdk-17 as build
WORKDIR /workspace/app

COPY pom.xml .
COPY src src

RUN mvn install -DskipTests=true
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)

FROM openjdk:17-jdk-alpine

VOLUME /tmp
ARG DEPENDENCY=target/dependency
ARG DEPENDENCY=/workspace/app/target/dependency
COPY --from=build ${DEPENDENCY}/BOOT-INF/lib/ /app/lib
COPY --from=build ${DEPENDENCY}/BOOT-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT [ "java","-cp", "app:app/lib/*","com.chamorrogarciasergio.pdam.gomarizacapilarapp.GomarizaCapilarAppApplication" ]